name: SCAutoBackup
version: 1.2.0
main: com.alexogden.core.SCAutoBackup
description: SkyCraft World Backup Utility
author: Alex Ogden
website: https://github.com/AlexOgden
api-version: '1.20'

commands:
  scab:
    description: Manually Trigger a Backup or Save
    usage: /scab <save | backup | pause | resume>
    permission: scbackup.admin